src/main/java/com/sparta/oishitable/global/exception/CustomRuntimeException.java, src/main/java/com/sparta/oishitable/global/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorResponse.java
=> :sparkles: feat: GlobalExceptionHandler 추가

src/main/java/com/sparta/oishitable/domain/restaurant/controller/CustomerRestaurantController.java, src/main/java/com/sparta/oishitable/domain/restaurant/dto/response/RestaurantListResponse.java, src/main/java/com/sparta/oishitable/domain/restaurant/dto/response/RestaurantResponse.java, src/main/java/com/sparta/oishitable/domain/restaurant/service/CustomerRestaurantService.java, src/main/java/com/sparta/oishitable/domain/restaurant/service/RestaurantService.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java
=> [oishiTable 1차] 가게 상세/전체 조회 기능

src/main/java/com/sparta/oishitable/domain/restaurant/service/RestaurantService.java
=> :sparkles: feat: 레포지토리 참조

src/main/java/com/sparta/oishitable/domain/user/controller/UserController.java, src/main/java/com/sparta/oishitable/domain/user/dto/request/UserSignupRequest.java, src/main/java/com/sparta/oishitable/domain/user/dto/response/UserSignupResponse.java, src/main/java/com/sparta/oishitable/domain/user/repository/UserRepository.java, src/main/java/com/sparta/oishitable/domain/user/service/UserService.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java
#5 
-회원가입 API 구현
-PasswordEncoder는 빈 등록 전까지 NoOpPasswordEncoder 임시 사용
코드 유지보수성 및 가독성
개선해야될부분
=> :sparkles: feat: 유저 회원가입 기능 구현

src/main/java/com/sparta/oishitable/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/oishitable/domain/reservation/dto/ReservationCreateRequest.java, src/main/java/com/sparta/oishitable/domain/reservation/dto/UserCreateRequest.java, src/main/java/com/sparta/oishitable/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/oishitable/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/oishitable/domain/restaurantseat/repository/RestaurantSeatRepository.java, src/main/java/com/sparta/oishitable/domain/seatType/repository/SeatTypeRepository.java, src/main/java/com/sparta/oishitable/global/exception/NotFoundException.java
#7 
예약 생성 기능을 추가했습니다
가독성 한번 봐주세요
나중에 controller 부분 수정해야합니다.
=> :sparkles: feat: 예약 생성 기능 추가

src/main/java/com/sparta/oishitable/domain/restaurant/service/OwnerRestaurantService.java, src/main/java/com/sparta/oishitable/domain/restaurantseat/repository/RestaurantSeatRepository.java, src/main/java/com/sparta/oishitable/domain/restaurantseat/service/RestaurantSeatService.java
#19 
- 가게 삭제 시 RestaurantSeat 테이블 내 레코드들 삭제 로직 추가 (간단 구현)
=> :bug: fix: 가게 삭제 API 수정

src/main/java/com/sparta/oishitable/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/oishitable/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/oishitable/domain/reservation/service/ReservationService.java
=> :sparkles: feat: 예약 취소

src/main/java/com/sparta/oishitable/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java
=> :recycle: feat: 에러코드 수정

src/main/java/com/sparta/oishitable/domain/comment/controller/CommentController.java, src/main/java/com/sparta/oishitable/domain/comment/dto/request/CommentCreateRequest.java, src/main/java/com/sparta/oishitable/domain/comment/dto/response/CommentResponse.java, src/main/java/com/sparta/oishitable/domain/comment/repository/CommentRepository.java, src/main/java/com/sparta/oishitable/domain/comment/service/CommentService.java
=> 댓글 생성 기능 추가

src/main/java/com/sparta/oishitable/domain/follow/controller/FollowController.java, src/main/java/com/sparta/oishitable/domain/follow/dto/request/FollowRequest.java, src/main/java/com/sparta/oishitable/domain/follow/dto/response/FollowResponse.java, src/main/java/com/sparta/oishitable/domain/follow/dto/response/FollowUserResponse.java, src/main/java/com/sparta/oishitable/domain/follow/entity/Follow.java, src/main/java/com/sparta/oishitable/domain/follow/repository/FollowRepository.java, src/main/java/com/sparta/oishitable/domain/follow/service/FollowService.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java
#22 
-팔로우/언팔로우 요청 처리
-팔로워/팔로잉 목록 조회
-팔로워/팔로잉 수 조회
-팔로우 여부 확인
코드 유지보수 및 가독성
pageable을 사용하는데도 @Transactional(readOnly = true)을 사용해야 하는지?, 개선점
=> :sparkles: feat: 팔로워/팔로잉 기능 추가

src/main/java/com/sparta/oishitable/domain/reservation/dto/ReservationFindResponse.java, src/main/java/com/sparta/oishitable/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/oishitable/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/oishitable/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java
#49 
예약 생성 관련 쿠폰 기능
쿠폰 생성 기능
쿠폰 생성 기능 만들었는데 테이블을 처음에 따로 만들어 봤는데 그러면 erd도 수정해야 할거 같아서 예약 테이블에 적용하려 했습니다. 그러다 보니 기능부분이 할 수 있는게 별로 없어 할인쿠폰을 100장 예약생성시 받을 수 있도록 구현만 해놨습니다.
=> :sparkles: :feat 쿠폰 기능

src/main/java/com/sparta/oishitable/domain/auth/controller/AuthController.java, src/main/java/com/sparta/oishitable/domain/auth/dto/request/AuthSignupRequest.java, src/main/java/com/sparta/oishitable/domain/auth/service/AuthService.java
=> loginRequest 수정

src/main/java/com/sparta/oishitable/domain/customer/follow/controller/FollowController.java, src/main/java/com/sparta/oishitable/domain/customer/follow/service/FollowService.java
#60 
- urlBuilder반환
- 컨트롤러 메서드 이름 변경
컨벤션
=> urlBuilder반환, 메소드 컨벤션

src/main/java/com/sparta/oishitable/domain/customer/reservation/controller/ReservationController.java, src/main/java/com/sparta/oishitable/domain/customer/reservation/dto/ReservationCreateRequest.java, src/main/java/com/sparta/oishitable/domain/customer/reservation/dto/ReservationFindResponse.java, src/main/java/com/sparta/oishitable/domain/customer/reservation/entity/Reservation.java, src/main/java/com/sparta/oishitable/domain/customer/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/oishitable/domain/customer/reservation/service/ReservationService.java, src/main/java/com/sparta/oishitable/domain/owner/restaurantseat/repository/RestaurantSeatRepository.java, src/main/java/com/sparta/oishitable/domain/owner/restaurantseat/service/RestaurantSeatService.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java
=> 예약 기능 리펙토링

src/main/java/com/sparta/oishitable/domain/customer/restaurant/controller/CustomerRestaurantController.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/dto/response/NearbyRestaurantResponse.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/service/CustomerRestaurantService.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/entity/Restaurant.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/repository/RestaurantRepository.java
#67 
- 사용자의 현재 위치를 기반으로 가게를 조회하는 기능 추가
- 사용자가 원하는 반경 설정 추가
- 하버사인 공식 사용
=> GPS 기반 가까운 가게 검색 기능

src/main/java/com/sparta/oishitable/domain/customer/bookmark/controller/BookmarkController.java, src/main/java/com/sparta/oishitable/domain/customer/bookmark/dto/request/BookmarkUpdateRequest.java, src/main/java/com/sparta/oishitable/domain/customer/bookmark/dto/response/BookmarkDetails.java, src/main/java/com/sparta/oishitable/domain/customer/bookmark/dto/response/BookmarksFindResponse.java, src/main/java/com/sparta/oishitable/domain/customer/bookmark/entity/Bookmark.java, src/main/java/com/sparta/oishitable/domain/customer/bookmark/repository/BookmarkQRepository.java, src/main/java/com/sparta/oishitable/domain/customer/bookmark/repository/BookmarkQRepositoryImpl.java, src/main/java/com/sparta/oishitable/domain/customer/bookmark/service/BookmarkService.java, src/main/java/com/sparta/oishitable/domain/customer/collection/bookmark/controller/CollectionBookmarkController.java, src/main/java/com/sparta/oishitable/domain/customer/collection/bookmark/dto/request/CollectionBookmarksCreateRequest.java, src/main/java/com/sparta/oishitable/domain/customer/collection/bookmark/dto/response/CollectionBookmarksFindResponse.java, src/main/java/com/sparta/oishitable/domain/customer/collection/bookmark/repository/CollectionBookmarkQRepository.java, src/main/java/com/sparta/oishitable/domain/customer/collection/bookmark/repository/CollectionBookmarkQRepositoryImpl.java, src/main/java/com/sparta/oishitable/domain/customer/collection/bookmark/service/CollectionBookmarkService.java
#81 
- 유저 북마크 목록 조회 API 추가
- 유저 컬렉션 내 북마크 조회 API 추가
=> 유저 북마크, 컬렉션 내 북마크 목록 조회 기능 추가

src/main/java/com/sparta/oishitable/domain/owner/restaurant/entity/Restaurant.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/menus/service/MenuService.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/menus/vo/Menus.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java, src/main/java/com/sparta/oishitable/global/util/CalculatorUtil.java
#98 
- Menus 일급 컬렉션으로 관리
- 만 단위로 변환 로직 유틸 클래스로 분리
=> 메뉴 기능 리펙토링

src/main/java/com/sparta/oishitable/domain/common/user/repository/UserQRepository.java, src/main/java/com/sparta/oishitable/domain/common/user/repository/UserQRepositoryImpl.java, src/main/java/com/sparta/oishitable/domain/common/user/repository/UserRepository.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/entity/Restaurant.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/controller/OwnerRestaurantWaitingController.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/dto/request/WaitingQueueDeleteUserRequest.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/dto/response/WaitingQueueFindUsersResponse.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/dto/response/WaitingUserDetails.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/repository/OwnerWaitingRedisRepositoryImpl.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/service/OwnerRestaurantWaitingService.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java
#76 
사장용 가게 웨이팅 기능 구현
레디스 리스트로만 구현했습니다.
Waiting 테이블 추가하여 고도화 할 계획입니다.
1차로 봐주십쇼
=> 사장 가게 웨이팅 기능 구현

src/main/java/com/sparta/oishitable/domain/customer/coupon/controller/UserCouponController.java, src/main/java/com/sparta/oishitable/domain/customer/coupon/service/UserCouponService.java, src/main/java/com/sparta/oishitable/domain/owner/coupon/dto/request/CouponCreateRequest.java
=> :recycle: refactor: 쿠폰 커서기반

.github/workflows/cd.yml, build.gradle, docker-compose-prod.yaml, docker-compose.yml
#126 
CI CD 파일 작성
엘라스틱 서치 / health 체크하는 Spring Actuator
=> build.gradle 의존성 추가 및 CI CD 파일 작성

docker-compose-prod.yaml
=> :hammer: script: cd 파일 수정

docker-compose-prod.yaml
#126 
database 생성시 계정 비밀번호도 추가
=> docker-compose-prod.yaml 파일 수정

docker-compose-prod.yaml
=> compose-prod.yaml 파일 수정

build.gradle, src/main/java/com/sparta/oishitable/domain/customer/coupon/dto/UserCouponResponse.java, src/main/java/com/sparta/oishitable/domain/customer/coupon/service/UserCouponService.java, src/main/java/com/sparta/oishitable/domain/owner/coupon/service/OwnerCouponService.java, src/main/java/com/sparta/oishitable/global/config/CacheConfig.java
=> :recycle: feat: 쿠폰 캐싱

src/main/java/com/sparta/oishitable/global/config/RedisConfig.java
#126 
redis config에서 프로퍼티를 받아오지 않아 기본값인 localhost 들어가는 구조 변경
=> redisConfig 수정

src/main/java/com/sparta/oishitable/domain/customer/bookmark/controller/BookmarkController.java, src/main/java/com/sparta/oishitable/domain/customer/bookmark/service/BookmarkService.java, src/main/java/com/sparta/oishitable/domain/customer/collection/bookmark/controller/CollectionBookmarkController.java, src/main/java/com/sparta/oishitable/domain/customer/collection/bookmark/service/CollectionBookmarkService.java, src/main/java/com/sparta/oishitable/domain/customer/collection/controller/CollectionController.java, src/main/java/com/sparta/oishitable/domain/customer/collection/service/CollectionService.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/controller/CustomerRestaurantWaitingController.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/repository/CustomerWaitingRedisRepository.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/repository/CustomerWaitingRedisRepositoryImpl.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/service/CustomerRestaurantWaitingService.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/entity/Restaurant.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/controller/OwnerRestaurantWaitingController.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/dto/request/WaitingQueueDeleteRequest.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/entity/WaitingType.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/service/OwnerRestaurantWaitingService.java, src/main/java/com/sparta/oishitable/global/aop/aspect/RedissonLockAspect.java
#143 
- 웨이팅 입장 API 동시성 처리: 분산락
- 변수명 변경
=> 웨이팅 입장 API 동시성 처리: 분산락

.github/workflows/cd.yml
#150 
무중단 배포 롤링 전략 채택
다음과 같은 단계로 진행
- cd 파이프라인에서 S3로 .env 파일과 docker-compose-prod.yaml 파일 업로드
- ASG의 template에서 스크립트를 작성하여 인스턴스 생성시 S3에서 위 파일들을 다운로드 하도록 설정
- docker 와 docker-compose 패키지를 다운로드 하여 컨테이너 실행
- 롤링의 Refresh 를 통해 새인스턴스를 하나 생성하고 완료되면 로드밸런서에 추가
- 나머지 기존 인스턴스도 해당 단계 거친후 완료되면 로드밸런서에 추가하는 식으로 배포 진행
롤링의 경우 롤백을 보다 세밀하게 설정해야한다는 문제가 있어서 이 후 개선해야 할듯
=> 롤링 전략을 이용한 무중단 배포 구현

src/main/java/com/sparta/oishitable/domain/auth/kakao/service/KakaoService.java
=> 카카오 전화번호 파싱

build.gradle, src/main/java/com/sparta/oishitable/global/config/RedissonConfig.java
=> redisson config 추가

src/main/java/com/sparta/oishitable/OishiTableApplication.java
=> redisson 자동 빈 설정 제외

src/main/java/com/sparta/oishitable/OishiTableApplication.java, src/main/java/com/sparta/oishitable/global/config/RedisConfig.java
=> redisconfig 에서 프로퍼티 변수 이름 명시 잘못 선언한것 수정

src/main/java/com/sparta/oishitable/global/config/RedissonConfig.java
=> redissonconfig 에서 프로퍼티 변수 이름 명시 잘못 선언한것 수정

src/main/java/com/sparta/oishitable/OishiTableApplication.java
=> redisson 자동설정 제외

docker-compose-prod.yaml
redisson이 spring boot 내부 클래스의 private 멤버에 접근하게끔 변경
=> docker-compose.yaml 수정

src/main/java/com/sparta/oishitable/OishiTableApplication.java
=> redisconfiguration 수정

docker-compose-prod.yaml
=> docker compose 수정

build.gradle, docker-compose-prod.yaml
redisson 3.23.5 로 업그레이드하여 redis 클러스터 정보를 반영할때 오류가 발생하는 버그 방지
=> redisson 수정

src/main/java/com/sparta/oishitable/global/config/RedissonConfig.java
=> :recycle: refactor: redissonConfig 수정

src/main/java/com/sparta/oishitable/global/config/RedissonConfig.java
=> redissonconfig 재생성

docker-compose.yml
=> docker-compose 파일 수정

docker-compose.yml
=> :recycle: refactor: docker-compose 파일 수정

src/main/java/com/sparta/oishitable/domain/auth/kakao/service/KakaoService.java
=> kakao 로그인 로그 추가

docker-compose-prod.yaml, src/main/java/com/sparta/oishitable/domain/common/user/entity/User.java
=> 서버 디버깅용 수정

src/main/java/com/sparta/oishitable/domain/customer/post/service/PostElasticService.java
=> :recycle: refactor: Base64로 인코딩으로 다시 변경

src/main/java/com/sparta/oishitable/domain/customer/post/entity/PostDocument.java
#127
날짜형태를 시 분 초 까지 인덱스에 저장하게끔 수정
=> 엘라스틱서치 인덱스 날짜 형태 변경

src/main/java/com/sparta/oishitable/domain/customer/post/entity/PostDocument.java
#127 
DB에 저장된 나노초까지 저장된 날짜를 초까지 잘라서 사용
=> 엘라스틱 서치 문서 수정

src/main/java/com/sparta/oishitable/domain/customer/coupon/service/UserCouponService.java, src/main/java/com/sparta/oishitable/domain/owner/coupon/service/OwnerCouponService.java, src/test/java/com/sparta/oishitable/domain/owner/coupon/service/OwnerCouponServiceTest.java
#206 
분산락적용 및 쿠폰생성 관련 테스트 코드 작성
=> :sparkles: feat:분산락 적용,쿠폰생성 테스트 코드

src/main/java/com/sparta/oishitable/domain/auth/kakao/service/KakaoService.java, src/main/java/com/sparta/oishitable/domain/common/auth/dto/request/AccessTokenReissueReq.java, src/main/java/com/sparta/oishitable/domain/common/auth/service/AuthService.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/repository/CustomerRestaurantRepositoryQuerydslImpl.java, src/main/java/com/sparta/oishitable/global/security/JwtTokenProvider.java, src/main/resources/static/css/front.css, src/main/resources/static/js/main/index.js, src/main/resources/static/js/main/login.js, src/main/resources/templates/main/index.html
=> 프론트 백엔드 연결

src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/controller/CustomerRestaurantWaitingController.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/dto/response/WaitingQueueCheckUserResponse.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/service/CustomerRestaurantWaitingJoinService.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/service/CustomerRestaurantWaitingService.java
#143 
- 웨이팅 대기열 입장 API 분산락 종료 시점 수정
- 웨이팅대기열 입장 API 요청 전 입장 가능 상태 체킹 API 추가
=> 웨이팅 관련 API 수정 및 추가

src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/service/CustomerRestaurantWaitingJoinService.java, src/main/java/com/sparta/oishitable/domain/customer/restaurant/waiting/service/CustomerRestaurantWaitingService.java, src/main/java/com/sparta/oishitable/domain/customer/waiting/controller/WaitingController.java, src/main/java/com/sparta/oishitable/domain/customer/waiting/dto/response/WaitingInfoResponse.java, src/main/java/com/sparta/oishitable/domain/customer/waiting/dto/response/WaitingInfosFindResponse.java, src/main/java/com/sparta/oishitable/domain/customer/waiting/repository/WaitingQueryDslRepository.java, src/main/java/com/sparta/oishitable/domain/customer/waiting/repository/WaitingQueryDslRepositoryImpl.java, src/main/java/com/sparta/oishitable/domain/customer/waiting/repository/WaitingRepository.java, src/main/java/com/sparta/oishitable/domain/customer/waiting/service/WaitingService.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/entity/Restaurant.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/entity/RestaurantWaitingStatus.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/controller/OwnerRestaurantWaitingController.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/dto/response/WaitingDetails.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/entity/Waiting.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/entity/WaitingStatus.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/repository/OwnerRestaurantWaitingRedisRepository.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/repository/OwnerRestaurantWaitingRedisRepositoryImpl.java, src/main/java/com/sparta/oishitable/domain/owner/restaurant/waiting/service/OwnerRestaurantWaitingService.java, src/main/java/com/sparta/oishitable/global/exception/error/ErrorCode.java
=> 웨이팅 대기 중인 유저 입장 요청, 입장 완료 API 구현

src/main/java/com/sparta/oishitable/domain/common/auth/service/AuthService.java
=> 레디스에 저장하는 토큰 형식 변경

src/main/java/com/sparta/oishitable/domain/common/auth/service/AuthService.java, src/main/java/com/sparta/oishitable/domain/common/kakao/service/KakaoService.java
=> refreshToken 키 값 변경

src/main/java/com/sparta/oishitable/domain/common/notification/service/EmailService.java
=> 이메일 완료 로그 추가
